added song model
raulgavris/musichub pull request #35
Opened 2020-11-11 07:39 UTC by andreealeu

2020-11-14 21:59 UTC, mirceachira requested changes

2020-11-15 09:34 UTC, mirceachira requested changes
@andreealeu am incercat sa rulez "npm run build" sa pot vedea schimbari dar imi zice:
"Cannot find module: 'bootstrap/dist/css/bootstrap.css'. Make sure this package is installed."
Oare mai tre sa dai add la ceva sau imi lipseste mie ceva / fac gresit?

2020-11-15 09:34 UTC, mirceachira commented on backend/main/settings.py
> +        'USER': os.environ.get('MYSQL_USER', 'andreea'),
daca dai merge la pull request toata lumea o sa aiba user-ul asta, ai avut probleme cu root?

2020-11-15 12:33 UTC, andreealeu commented on backend/main/settings.py
> +        'USER': os.environ.get('MYSQL_USER', 'andreea'),
am avut probleme cu  root, dar np il schimb si pun asa cu root si le rezolv eu dupa
that bootstrap thing, eu am folosit Container, Row si Col din reactstrap dar fara impotrul ala nu functioneaza din pacate
nu tin minte exact dar cred ca am instalat bootstrap sa mearga (npm install --save bootstrap)

2020-11-15 12:34 UTC, andreealeu commented on backend/web_api/views/song_view.py
> +        # not sure what the post req should look like now.
ok I will change it to TODO sa fie mai ok :))

2020-11-15 12:35 UTC, andreealeu commented on backend/web_api/models/song_model.py
> +    user_location = models.CharField(max_length=20)
hmm could I do this for next iteration ? stiu ca asa trebuie , dar cred ca complica putin cum trimit datele pe frontend pt afisare. adica acum trimit toata lista de songs si o afisez, asa ar trebui cumva sa trimit cu fiecare song si useru corespunzator , rite ?

2020-11-15 12:41 UTC, andreealeu commented
mai este o chestie, cum era structurat dupa requesturi ii chestia aia cu 'loaded' in state
o sa o scot  la paginile care nu au get/post, dar deocamdata am lasat-o si se initializeaza cu true si atunci se afiseaza tot ok :))

2020-11-15 21:57 UTC, merged